### ISSUE TITLE
「よく使うリアクションのサジェスト」からスタンプが押せなくなりました

### ISSUE THREAD

**Issue by miyashita-reika** [Nishihara-Daiki/chat-helper#2]
お疲れ様です。宮下です。
chat-helperの作成ありがとうございます。使いやすく、アップデートも楽しみにしています！

掲題の件につきまして確認したくご連絡させていただきました。
昨日くらいから「よく使うリアクションのサジェスト」からスタンプが押せなくなりました。
サジェストでない部分から押すことはできますが、可能であればご確認お願いいたします。

**Comment by Nishihara-Daiki** [comment]
issue ありがとうございます。本件、Google Chat 側の仕様変更に起因するものだと推測しています。
昨日は時間が取れませんでしたが、近いうちに修正予定です。

**Comment by Nishihara-Daiki** [comment]
修正しました (v0.1.10)
